title: "Suhail Patel"
email: "ipatelsuhail@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Cloudera CDP Certified Solution Architect with over 9 years of experience in Linux, Big Data, Cloud, and DevOps technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://isuhailpatel.github.io" # the base hostname & protocol for your site
twitter_username: your_twitter_handle
github_username: isuhailpatel
minimal_mistakes_skin: "dark"
